# Generated by Django 4.0.1 on 2022-01-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_is_activate_movie_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='stars',
            new_name='value',
        ),
    ]
